/**
 * API reference, generated by walking the live Express router.
 *
 * Introspection rather than a hand-written list, because a hand-written list
 * is wrong the first time somebody adds a route and forgets to update it.
 * What cannot be introspected - what an endpoint is for, and who may call it -
 * is annotated below and matched onto the discovered paths by prefix.
 */
import { Router } from 'express';
import env from '../config/env.js';

const router = Router();

/**
 * Express mount patterns are dense with backslashes, so these are built with
 * RegExp + String.raw rather than literals - it keeps them readable and
 * exactly escaped.
 */
const TRAILING_GUARD = new RegExp(String.raw`\\\/\?\(\?=\\\/\|\$\)`);
const LEADING_SLASH = new RegExp(String.raw`^\^\\\/`);
const PARAM_GROUP = new RegExp(String.raw`\(\?:\(\[\^\\\/\]\+\?\)\)`, 'g');
const ESCAPED_SLASH = new RegExp(String.raw`\\\/`, 'g');

/** Turns an Express mount regexp back into the path it came from. */
function decodeMountPath(layer) {
  if (layer.path) return layer.path;

  const source = layer.regexp && layer.regexp.source;
  if (!source) return '';
  if (source === String.raw`^\/?$`) return '';

  const cleaned = source
    .replace(TRAILING_GUARD, '')
    .replace(LEADING_SLASH, '/')
    .replace(PARAM_GROUP, ':param')
    .replace(ESCAPED_SLASH, '/')
    .replace(/\$$/, '');

  return cleaned === '/' ? '' : cleaned;
}

/** Restores the :params Express replaced with capture groups. */
function restoreParams(path, keys) {
  if (!keys || !keys.length) return path;

  let index = 0;
  return path.replace(/:param/g, () => {
    const key = keys[index];
    index += 1;
    return ':' + (key && key.name ? key.name : 'param');
  });
}

function walk(stack, prefix = '', out = []) {
  for (const layer of stack) {
    if (layer.route) {
      const methods = Object.keys(layer.route.methods)
        .filter((m) => m !== '_all')
        .map((m) => m.toUpperCase());

      const path = (prefix + layer.route.path).replace(/\/+/g, '/').replace(/\/$/, '') || '/';
      for (const method of methods) out.push({ method, path });
      continue;
    }

    if (layer.name === 'router' && layer.handle && layer.handle.stack) {
      const mount = restoreParams(decodeMountPath(layer), layer.keys);
      walk(layer.handle.stack, prefix + mount, out);
    }
  }

  return out;
}

/**
 * What each area is for and who may reach it.
 * Ordered longest-prefix first, so /admin/kyc is not swallowed by /admin.
 */
const AREAS = [
  { prefix: '/admin/reports', name: 'Admin: reports', access: 'Admin', description: 'Row-level service and payout reports, filterable and exportable as CSV.' },
  { prefix: '/admin/kyc', name: 'Admin: verification', access: 'Admin', description: 'KYC review queue, approve, reject and suspend.' },
  { prefix: '/admin/reviews', name: 'Admin: moderation', access: 'Admin', description: 'Review moderation queue and decisions.' },
  { prefix: '/admin/disputes', name: 'Admin: disputes', access: 'Admin', description: 'Dispute assignment and resolution with refunds.' },
  { prefix: '/admin/analytics', name: 'Admin: analytics', access: 'Admin', description: 'Platform dashboards, time series and leaderboards.' },
  { prefix: '/admin/settings', name: 'Admin: settings', access: 'Admin', description: 'Commission, payout, cancellation and tax configuration.' },
  { prefix: '/admin/payouts', name: 'Admin: payouts', access: 'Admin', description: 'Payout preview, batch runs and history.' },
  { prefix: '/providers/search', name: 'Discovery', access: 'Public', description: 'Provider search with category, location, price and rating filters.' },
  { prefix: '/providers/me', name: 'Provider self-service', access: 'Provider', description: 'Profile, services offered, service areas and the weekly schedule.' },
  { prefix: '/providers', name: 'Provider profiles', access: 'Public', description: 'Public provider profile, availability slots and reviews.' },
  { prefix: '/auth', name: 'Authentication', access: 'Public, then signed in', description: 'Registration, sign-in, OTP confirmation, token refresh and password management.' },
  { prefix: '/categories', name: 'Service catalogue', access: 'Public read, admin write', description: 'Service categories, the two-level tree and the admin pricing guidelines.' },
  { prefix: '/kyc', name: 'Verification', access: 'Provider', description: 'KYC submission and document upload.' },
  { prefix: '/bookings', name: 'Bookings and jobs', access: 'Customer, provider, admin (scoped)', description: 'Booking lifecycle from request through completion, plus live tracking.' },
  { prefix: '/payments', name: 'Payments', access: 'Customer, admin', description: 'Payment orders, status and admin-issued refunds.' },
  { prefix: '/invoices', name: 'Invoices', access: 'Customer, provider, admin', description: 'Invoices for completed and paid bookings.' },
  { prefix: '/earnings', name: 'Earnings', access: 'Provider', description: 'Provider balance and the earnings ledger.' },
  { prefix: '/reviews', name: 'Reviews', access: 'Customer, provider', description: 'Leaving reviews, provider replies and reporting.' },
  { prefix: '/disputes', name: 'Disputes', access: 'Customer, provider, admin', description: 'Raising and discussing a dispute on a completed booking.' },
  { prefix: '/webhooks', name: 'Webhooks', access: 'Gateway (signature authenticated)', description: 'Payment gateway callbacks, verified by HMAC over the raw body.' },
  { prefix: '/files', name: 'Signed files', access: 'Signature authenticated', description: 'Private file delivery. The short-lived signature is the authorisation.' },
];

function areaFor(path) {
  const relative = path.replace(env.API_PREFIX, '');
  return AREAS.find((a) => relative.startsWith(a.prefix));
}

router.get('/', (req, res) => {
  const routes = walk(req.app._router.stack)
    .filter((r) => r.path.startsWith(env.API_PREFIX) || r.path.startsWith('/health'))
    .filter((r) => !r.path.endsWith('/docs'))
    .sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));

  const grouped = new Map();

  for (const route of routes) {
    const area = areaFor(route.path);
    const key = area ? area.name : 'Health and service info';

    if (!grouped.has(key)) {
      grouped.set(key, {
        name: key,
        access: area ? area.access : 'Public',
        description: area ? area.description : 'Liveness, readiness and the service index.',
        endpoints: [],
      });
    }

    grouped.get(key).endpoints.push(route.method + ' ' + route.path);
  }

  res.json({
    success: true,
    service: 'ServiceMitra API',
    version: 'v1',
    baseUrl: env.API_PREFIX,
    conventions: {
      success: '{ success: true, message, data, meta? }',
      error: '{ success: false, error: { code, message, details? }, requestId }',
      auth: 'Bearer access token in the Authorization header; refresh token in the HttpOnly sst_refresh cookie',
      money: 'All amounts are integer minor units (paise). Fields ending in Minor are authoritative.',
      pagination: 'page and limit query parameters, with totals in meta',
      correlation: 'Every response carries X-Request-Id; send your own to thread it through your logs',
    },
    areas: [...grouped.values()],
    endpointCount: routes.length,
  });
});

export default router;
